# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
	# check these on https://modmuss50.me/fabric.html
	minecraft_version=1.21.9
	yarn_mappings=1.21.9+build.1
	loader_version=0.17.2
    loom_version=1.11-SNAPSHOT

# Mod Properties
	mod_version = 2.6.0+mc1.21.9
	maven_group = eu.reinalter.noah
	archives_base_name = UseServerName

# Dependencies
	# Fabric API
    fabric_version = 0.134.0+1.21.9
	# Modmenu
	modmenu_version = 16.0.0-rc.1
	# Cloth-Config
	yacl_version = 3.8.0+1.21.9
	# Bobby
	bobby_version = xiXouhmS
	# Xaero's Minimap
	xaero_minimap_version = NDNq9HeR
	# Xaero's Worldmap
	xaero_worldmap_version = 81Qc21E2
	# Distant Horizons
	distant_horizons_version = 9yaYzpcr
